services:
  backend:
    image: backend
    container_name: backend
    ports:
      - "4000:3000"
    restart: always
    depends_on:
      - mysql

  frontend:
    image: frontend
    container_name: frontend
    ports:
      - "5000:80"
    restart: always
    depends_on:
      - backend

  mysql:
    container_name: mysql
    image: mysql:8.3.0
    restart: always
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: recyclovision
      MYSQL_ROOT_PASSWORD: recyclovision@123456
    ports:
      - 3306:3306

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8088:80"
    restart: always
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql

volumes:
  mysql-volume:
