services:
  backend:
    image: 381491905102.dkr.ecr.us-east-1.amazonaws.com/recyclovision/backend:latest
    container_name: backend
    ports:
      - "3000"
    restart: always
    depends_on:
      - mysql-r
    networks:
      - prometheus

    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}

  frontend:
    image: 381491905102.dkr.ecr.us-east-1.amazonaws.com/recyclovision/frontend:latest
    container_name: frontend
    ports:
      - "80"
    restart: always
    depends_on:
      - backend
    networks:
      - prometheus

  mysql-r:
    container_name: mysql-r
    image: mysql:8.3.0
    restart: always
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: recyclovision
      MYSQL_ROOT_PASSWORD: recyclovision@123456
    ports:
      - "3306"
    networks:
      - prometheus

  phpmyadmin-r:
    container_name: phpmyadmin-r
    image: phpmyadmin/phpmyadmin
    ports:
      - "80"
    restart: always
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql-r
    networks:
      - prometheus

networks:
  prometheus:
    name: prometheus
    external: true

volumes:
  mysql-volume:
